[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib", "rlib"]

[dependencies]
wasm-bindgen="0.2.63"
language = { path = "../language" }
console_error_panic_hook = "0.1.7"
serde-wasm-bindgen = "0.6.5"
serde = "1.0.219"
serde_json = "1.0.140"
